// @generated by protoc-gen-es v2.6.1
// @generated from file user-profile.proto (package profile, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user-profile.proto.
 */
export declare const file_user_profile: GenFile;

/**
 * @generated from message profile.Empty
 */
export declare type Empty = Message<"profile.Empty"> & {
};

/**
 * Describes the message profile.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export declare const EmptySchema: GenMessage<Empty>;

/**
 * @generated from message profile.ViewProfileResponse
 */
export declare type ViewProfileResponse = Message<"profile.ViewProfileResponse"> & {
  /**
   * @generated from field: string firstName = 1;
   */
  firstName: string;

  /**
   * @generated from field: string lastName = 2;
   */
  lastName: string;

  /**
   * @generated from field: string emailId = 3;
   */
  emailId: string;

  /**
   * @generated from field: int32 age = 4;
   */
  age: number;

  /**
   * @generated from field: string gender = 5;
   */
  gender: string;

  /**
   * @generated from field: string skills = 6;
   */
  skills: string;

  /**
   * @generated from field: string photourl = 7;
   */
  photourl: string;
};

/**
 * Describes the message profile.ViewProfileResponse.
 * Use `create(ViewProfileResponseSchema)` to create a new message.
 */
export declare const ViewProfileResponseSchema: GenMessage<ViewProfileResponse>;

/**
 * @generated from service profile.ProfileService
 */
export declare const ProfileService: GenService<{
  /**
   * @generated from rpc profile.ProfileService.ViewProfile
   */
  viewProfile: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof ViewProfileResponseSchema;
  },
}>;

