// @generated by protoc-gen-es v2.6.1
// @generated from file user-auth.proto (package auth, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file user-auth.proto.
 */
export const file_user_auth = /*@__PURE__*/
  fileDesc("Cg91c2VyLWF1dGgucHJvdG8SBGF1dGgiBwoFRW1wdHkiNQoQVXNlckxvZ2luUmVxdWVzdBIPCgdlbWFpbElkGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIiAKDFVzZXJSZXNwb25zZRIQCghyZXNwb25zZRgBIAEoCSJbChFVc2VyU2lnblVwUmVxdWVzdBIRCglmaXJzdE5hbWUYASABKAkSEAoIbGFzdE5hbWUYAiABKAkSDwoHZW1haWxJZBgDIAEoCRIQCghwYXNzd29yZBgEIAEoCTKBAQoLYXV0aFNlcnZpY2USNwoJVXNlckxvZ0luEhYuYXV0aC5Vc2VyTG9naW5SZXF1ZXN0GhIuYXV0aC5Vc2VyUmVzcG9uc2USOQoKVXNlclNpZ25VcBIXLmF1dGguVXNlclNpZ25VcFJlcXVlc3QaEi5hdXRoLlVzZXJSZXNwb25zZWIGcHJvdG8z");

/**
 * Describes the message auth.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema = /*@__PURE__*/
  messageDesc(file_user_auth, 0);

/**
 * Describes the message auth.UserLoginRequest.
 * Use `create(UserLoginRequestSchema)` to create a new message.
 */
export const UserLoginRequestSchema = /*@__PURE__*/
  messageDesc(file_user_auth, 1);

/**
 * Describes the message auth.UserResponse.
 * Use `create(UserResponseSchema)` to create a new message.
 */
export const UserResponseSchema = /*@__PURE__*/
  messageDesc(file_user_auth, 2);

/**
 * Describes the message auth.UserSignUpRequest.
 * Use `create(UserSignUpRequestSchema)` to create a new message.
 */
export const UserSignUpRequestSchema = /*@__PURE__*/
  messageDesc(file_user_auth, 3);

/**
 * @generated from service auth.authService
 */
export const authService = /*@__PURE__*/
  serviceDesc(file_user_auth, 0);

