// @generated by protoc-gen-es v2.6.1
// @generated from file user-auth.proto (package auth, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user-auth.proto.
 */
export declare const file_user_auth: GenFile;

/**
 * @generated from message auth.Empty
 */
export declare type Empty = Message<"auth.Empty"> & {
};

/**
 * Describes the message auth.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export declare const EmptySchema: GenMessage<Empty>;

/**
 * @generated from message auth.UserLoginRequest
 */
export declare type UserLoginRequest = Message<"auth.UserLoginRequest"> & {
  /**
   * @generated from field: string emailId = 1;
   */
  emailId: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.UserLoginRequest.
 * Use `create(UserLoginRequestSchema)` to create a new message.
 */
export declare const UserLoginRequestSchema: GenMessage<UserLoginRequest>;

/**
 * @generated from message auth.UserResponse
 */
export declare type UserResponse = Message<"auth.UserResponse"> & {
  /**
   * @generated from field: string response = 1;
   */
  response: string;
};

/**
 * Describes the message auth.UserResponse.
 * Use `create(UserResponseSchema)` to create a new message.
 */
export declare const UserResponseSchema: GenMessage<UserResponse>;

/**
 * @generated from message auth.UserSignUpRequest
 */
export declare type UserSignUpRequest = Message<"auth.UserSignUpRequest"> & {
  /**
   * @generated from field: string firstName = 1;
   */
  firstName: string;

  /**
   * @generated from field: string lastName = 2;
   */
  lastName: string;

  /**
   * @generated from field: string emailId = 3;
   */
  emailId: string;

  /**
   * @generated from field: string password = 4;
   */
  password: string;
};

/**
 * Describes the message auth.UserSignUpRequest.
 * Use `create(UserSignUpRequestSchema)` to create a new message.
 */
export declare const UserSignUpRequestSchema: GenMessage<UserSignUpRequest>;

/**
 * @generated from service auth.authService
 */
export declare const authService: GenService<{
  /**
   * @generated from rpc auth.authService.UserLogIn
   */
  userLogIn: {
    methodKind: "unary";
    input: typeof UserLoginRequestSchema;
    output: typeof UserResponseSchema;
  },
  /**
   * @generated from rpc auth.authService.UserSignUp
   */
  userSignUp: {
    methodKind: "unary";
    input: typeof UserSignUpRequestSchema;
    output: typeof UserResponseSchema;
  },
}>;

