// @generated by protoc-gen-es v2.6.1
// @generated from file user-con-req.proto (package userConnReq, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user-con-req.proto.
 */
export declare const file_user_con_req: GenFile;

/**
 * @generated from message userConnReq.SendConection
 */
export declare type SendConection = Message<"userConnReq.SendConection"> & {
  /**
   * @generated from field: string emailId = 1;
   */
  emailId: string;

  /**
   * @generated from field: string status = 2;
   */
  status: string;
};

/**
 * Describes the message userConnReq.SendConection.
 * Use `create(SendConectionSchema)` to create a new message.
 */
export declare const SendConectionSchema: GenMessage<SendConection>;

/**
 * @generated from message userConnReq.ConnectionResponse
 */
export declare type ConnectionResponse = Message<"userConnReq.ConnectionResponse"> & {
  /**
   * @generated from field: string success = 1;
   */
  success: string;
};

/**
 * Describes the message userConnReq.ConnectionResponse.
 * Use `create(ConnectionResponseSchema)` to create a new message.
 */
export declare const ConnectionResponseSchema: GenMessage<ConnectionResponse>;

/**
 * @generated from service userConnReq.ConnService
 */
export declare const ConnService: GenService<{
  /**
   * @generated from rpc userConnReq.ConnService.SendRequest
   */
  sendRequest: {
    methodKind: "unary";
    input: typeof SendConectionSchema;
    output: typeof ConnectionResponseSchema;
  },
}>;

